### ISSUE TITLE
issue with load_observing_metadata in config.py

### ISSUE THREAD

**Issue by steigersg** [MazinLab/MKIDCore#1]
When trying to run the whole pipeline, on the creation of the last .h5 file this error appears: 

File "/home/steigersg/src/mkidpipeline/mkidpipeline/config.py", line 620, in load_observing_metadata
    files = list(files) + glob(os.path.join(config.paths.database), 'obslog*.json')
TypeError: glob() takes 1 positional argument but 2 were given

**Comment by baileyji** [comment]
That should be `files = list(files) + glob(os.path.join(config.paths.database, 'obslog*.json'))`
