### ISSUE TITLE
Numpy 2.0 Incompatibility 

### ISSUE THREAD

**Issue by nzivkov** [MazinLab/MKIDCore#13]
Unable to pipx install mkidpipeline due to incompatibility between numpy 2.0 and python 3.9/3.10.

**Comment by ld-cd** [comment]
Numpy 2.0.0 _should_ have support for python 3.9 and 3.10, what was the output of the install error?

**Comment by ld-cd** [comment]
https://numpy.org/news/ It was 2.1 that dropped 3.9 support

**Comment by ld-cd** [comment]
Ok glados is trying to use 3.8, I don't have this on the python supported list because I also had issues, maybe I'll need to make it work or just finally update glados

**Comment by ld-cd** [comment]
Ok the following should work properly on glados and dark (but you will need to uninstall your wheatley install if you want it there, I will try and resolve this at some point in the next week or so)
```
pipx install --verbose ./MKIDPipeline --python `which python3.10`
```
