### ISSUE TITLE
batch_apply_metadata bug 

### ISSUE THREAD

**Issue by steigersg** [MazinLab/MKIDCore#2]
File "/home/steigersg/src/mkidpipeline/mkidpipeline/__init__.py", line 37, in batch_apply_metadata
    md.registerfromkvlist(ob.metadata.items())
AttributeError: 'list' object has no attribute 'registerfromkvlist'

variable 'md' should be of the class ConfigThing?

**Comment by ld-cd** [comment]
@nzivkov Can you confirm this no longer happens and if so close the issue

**Comment by nzivkov** [comment]
Tested and error is no longer present, md was a list variable but it is now an object
