### ISSUE TITLE
XKID Keyset does not actually exist on this branch

### ISSUE THREAD

**Issue by ld-cd** [MazinLab/MKIDCore#5]
https://github.com/MazinLab/MKIDCore/blame/fb5831f7d8728d7fd686cdc87fe0e22e9b7c8285/mkidcore/metadata.py#L172

**Comment by baileyji** [comment]
What is "this" branch?

**Comment by ld-cd** [comment]
`develop`, the branch tries to load the keyset but it's not actually committed on the branch

**Comment by ld-cd** [comment]
Resolved on main branch
